# Generated by Django 3.2.11 on 2022-01-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='skills',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
