# Generated by Django 3.2.7 on 2021-09-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='promo_video',
            field=models.URLField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
