# Generated by Django 3.2.7 on 2021-09-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='response_time',
            field=models.CharField(default='48', max_length=20),
        ),
    ]
