# Generated by Django 3.2.11 on 2022-02-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_tutorprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='subject_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
