# Generated by Django 3.2.7 on 2021-09-21 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=35)),
                ('message', models.TextField(max_length=200)),
                ('user_id', models.CharField(blank=True, max_length=10)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
        ),
    ]
