# Generated by Django 3.2.7 on 2021-09-23 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=15)),
                ('Interest', models.CharField(blank=True, max_length=45)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('collegeName', models.CharField(blank=True, max_length=60)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('wallet_amount', models.IntegerField(blank=True, default=10, null=True)),
                ('is_allowed_to_publish', models.BooleanField(default=False)),
                ('prime_user', models.BooleanField(default=False)),
                ('account_verified', models.BooleanField(default=False)),
                ('is_allowd_view_blog', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
