# Generated by Django 3.2.6 on 2021-08-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_allowd_view_blog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
