# Generated by Django 3.2.7 on 2021-09-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='account_verified',
            field=models.BooleanField(default=False),
        ),
    ]
