# Generated by Django 3.2.11 on 2022-01-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_connectionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='about_me',
            field=models.TextField(blank=True, max_length=700),
        ),
    ]
