# Generated by Django 3.2.11 on 2022-02-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentprofile_language_spoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttransaction',
            name='mobilenumber',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
